---
apiVersion: v1
kind: Pod
metadata:
  name: puppet
  labels: 
    app: puppet
spec:
  containers:
     - image: ubuntu-ssh:v1.0
       name: puppet
       ports:
         - containerPort: 22
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  namespace: default
  labels:
    app: puppet
spec:
  selector:
    app: puppet
  ports:
  - name: port-22-tcp
    protocol: TCP
    targetPort: 9022
    port: 22
