---
# this yml will install some common packages 
# and docker on all nodes(ie controller and workers)
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Install some packages
    apt: 
      name: [ 'vim',
              'git',
              'net-tools',
              'sudo',
              'sshpass',
              'curl',
              'gpg',
              'python3-apt',
              'python3-pip',
              'apt-transport-https'
      ]
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install python modules
    pip: 
      name: [ 
       'docker',
       'kubernetes==11.0.0',
       'openshift==0.11.0'
    ] 

  - name: Install docker
    apt:
      name: [ 'docker.io' ]
      update_cache: yes
      state: latest

  - name: Start docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Copy daemon configuration file for docker
    copy:
      src: template/daemon.json.j2
      dest: /etc/docker/daemon.json
    when: ansible_distribution == "Ubuntu" and
          ansible_distribution_release == "focal"
    notify:
      - Docker service

  handlers:
  - name: Docker service
    service:
      name: docker
      state: restarted
