---
- hosts: controller
  gather_facts: yes

  
  tasks:
  - name: Create folder to hold puppet pod related files
    file:
      path: /home/{{ user }}/files/puppet
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    tags: puppet
    
  - name: Place puppet-master file
    template:
      src: templates/puppet/puppet-master.yml.j2
      dest: /home/{{ user }}/files/puppet/puppet-master.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Place pu-dv1 pod files
    template:
      src: templates/puppet/pu-dv1.yml.j2
      dest: /home/{{ user }}/files/puppet/pu-dv1.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Place pu-dv2 pod files
    template:
      src: templates/puppet/pu-dv2.yml.j2
      dest: /home/{{ user }}/files/puppet/pu-dv2.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Place pu-pr1 pod files
    template:
      src: templates/puppet/pu-pr1.yml.j2
      dest: /home/{{ user }}/files/puppet/pu-pr1.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Place pu-pr2 pod files
    template:
      src: templates/puppet/pu-pr2.yml.j2
      dest: /home/{{ user }}/files/puppet/pu-pr2.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Place pu-pr3 pod files
    template:
      src: templates/puppet/pu-pr3.yml.j2
      dest: /home/{{ user }}/files/puppet/pu-pr3.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: puppet

  - name: Create folder to hold salt pod related files
    file:
      path: /home/{{ user }}/files/salt
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    tags: salt

  - name: Place salt-master file
    template:
      src: templates/salt/salt-master.yml.j2
      dest: /home/{{ user }}/files/salt/salt-master.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-dv1 minion file
    template:
      src: templates/salt/sa-dv1.yml.j2
      dest: /home/{{ user }}/files/salt/sa-dv1.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-dv2 minion file
    template:
      src: templates/salt/sa-dv2.yml.j2
      dest: /home/{{ user }}/files/salt/sa-dv2.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-dv3 minion file
    template:
      src: templates/salt/sa-dv3.yml.j2
      dest: /home/{{ user }}/files/salt/sa-dv3.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-pr1 minion file
    template:
      src: templates/salt/sa-pr1.yml.j2
      dest: /home/{{ user }}/files/salt/sa-pr1.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-pr2 minion file
    template:
      src: templates/salt/sa-pr2.yml.j2
      dest: /home/{{ user }}/files/salt/sa-pr2.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-pr3 minion file
    template:
      src: templates/salt/sa-pr3.yml.j2
      dest: /home/{{ user }}/files/salt/sa-pr3.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-pr4 minion file
    template:
      src: templates/salt/sa-pr4.yml.j2
      dest: /home/{{ user }}/files/salt/sa-pr4.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Place sa-pr5 minion file
    template:
      src: templates/salt/sa-pr5.yml.j2
      dest: /home/{{ user }}/files/salt/sa-pr5.yml
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    tags: salt

  - name: Create folder to volume related files
    file:
      path: /home/{{ user }}/files/volume
      state: directory
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Place volume related files
    template:
      src: templates/volume/volume.yml.j2
      dest: /home/{{ user }}/files/volume/volume.yml
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ user }}"

---
- hosts: compute
  gather_facts: yes


  tasks:
  - name: Create folder to hold docker related files
    file:
      path: /home/{{ user }}/files/dockerfiles
      state: directory
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Place supervisord.conf file
    template:
      src: templates/dockerfiles/supervisord.conf.j2
      dest: /home/{{ user }}/files/dockerfiles/supervisord.conf
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Place ubuntu-multiservice-Dockerfile file
    template:
      src: templates/dockerfiles/ubuntu-multiservice-Dockerfile.j2
      dest: /home/{{ user }}/files/dockerfiles/ubuntu-multiservice-Dockerfile
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'

  - name: Place ubuntu-ssh-only-Dockerfile file
    template:
      src: templates/dockerfiles/ubuntu-ssh-only-Dockerfile.j2
      dest: /home/{{ user }}/files/dockerfiles/ubuntu-ssh-only-Dockerfile
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
