---
- hosts: compute
  gather_facts: yes


  tasks:
  - name: Create folder to hold docker related files
    file:                                                                                                                 
      path: /home/{{ user }}/files/dockerfiles                                                                               
      state: directory                                                                                                                  
      mode: '0755'                                                                                                                      
      owner: "{{ user }}"                                                                                                            
      group: "{{ user }}"                                                                                                        

  - name: Place supervisord.conf file                                                                                                   
    template:                                                                                                                        
      src: templates/dockerfiles/supervisord.conf.j2                                                                                    
      dest: /home/{{ user }}/files/dockerfiles/supervisord.conf                                                                         
      mode: '0644'                                                                                                               
      owner: "{{ user }}"                                                                                                          
      group: "{{ user }}"                                                                                                                
  - name: Place ubuntu-multiservice-Dockerfile file
    template:
      src: templates/dockerfiles/ubuntu-multiservice-Dockerfile.j2
      dest: /home/{{ user }}/files/dockerfiles/ubuntu-multiservice-Dockerfile
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'

  - name: Place ubuntu-ssh-only-Dockerfile file
    template:
      src: templates/dockerfiles/ubuntu-ssh-only-Dockerfile.j2
      dest: /home/{{ user }}/files/dockerfiles/ubuntu-ssh-only-Dockerfile
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'

  - name: Build an ubuntu image only ssh running in it
    docker_image:
      name: ubuntu-ssh
      build:
        dockerfile: /home/{{ user }}/files/dockerfiles/ubuntu-ssh-only-Dockerfile
        path: /home/{{ user }}/files/dockerfiles
        source: build
        rm: yes
      pull: yes
      state: present
      tag: v1.0

  - name: Build an ubuntu image multi services running in it
    docker_image:
      name: ubuntu-multiservices
      build:
        dockerfile: /home/{{ user }}/files/dockerfiles/ubuntu-multiservice-Dockerfile
        path: /home/{{ user }}/files/dockerfiles
        source: build
        rm: yes
      pull: yes
      state: present
      tag: v1.0
