---
- hosts: controller1
  become: yes
  #remote_user: masum
  gather_facts: yes

  tasks:
  - name: Copy all deployments file
    copy:
      src: files/os
      dest: /root/
      owner: root
      group: root
        #dest: /tmp/
        #owner: masum 
        #group: masum
      mode: '0644'

  - name: Create a k8s namespace
    k8s:
      kubeconfig: /home/masum/.kube/config
      name: my-test
      api_version: v1
      kind: Namespace
      state: present 

  - name: Create PersistentVolume for pods
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present 
      src: /root/os/volume/volume.yml

  - name: Deploy salt-master
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /root/os/salt/salt-master.yml

  - name: Deploy salt-minions
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /root/os/salt/salt-minions.yml

  - name: Deploy pupet-master
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /root/os/puppet/puppet-master.yml

  - name: Deploy puppet-nodes
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /root/os/puppet/puppet-nodes.yml

        #  - name: Deploy jenkins
        #    k8s:
        #      kubeconfig: /home/masum/.kube/config
        #      namespace: default
        #      state: present
        #      src: /root/os/jenkins/jenkins.yml
