---
- hosts: controller
  become: yes
  gather_facts: yes

  tasks:
    #  - name: Create a k8s namespace
    #    k8s:
    #      kubeconfig: /home/masum/.kube/config
    #      name: my-test
    #      api_version: v1
    #      kind: Namespace
    #      state: present 
    #
    #  - name: Create PersistentVolume for pods
    #    k8s:
    #      kubeconfig: /home/masum/.kube/config
    #      namespace: default
    #      state: present 
    #      src: /home/{{ user }}/files/volume/volume.yml

  - name: Deploy sa-dv1 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv1.yml
    tags: salt

  - name: Deploy sa-dv2 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv2.yml
    tags: salt

  - name: Deploy sa-dv3 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv3.yml
    tags: salt

  - name: Deploy sa-pr1 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr1.yml
    tags: salt

  - name: Deploy sa-pr2 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr2.yml
    tags: salt

  - name: Deploy sa-pr3 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr3.yml
    tags: salt
