---
- hosts: controller
  become: yes
  gather_facts: yes

  tasks:
    #  - name: Create a k8s namespace
    #    k8s:
    #      kubeconfig: /home/masum/.kube/config
    #      name: my-test
    #      api_version: v1
    #      kind: Namespace
    #      state: present 
    #
    #  - name: Create PersistentVolume for pods
    #    k8s:
    #      kubeconfig: /home/masum/.kube/config
    #      namespace: default
    #      state: present 
    #      src: /home/{{ user }}/files/volume/volume.yml

  - name: Deploy salt-master
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/salt-master.yml
    tags: salt

  - name: Deploy sa-dv1 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv1.yml
    tags: salt

  - name: Deploy sa-dv2 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv2.yml
    tags: salt

  - name: Deploy sa-dv3 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-dv3.yml
    tags: salt

  - name: Deploy sa-pr1 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr1.yml
    tags: salt

  - name: Deploy sa-pr2 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr2.yml
    tags: salt

  - name: Deploy sa-pr3 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr3.yml
    tags: salt

  - name: Deploy sa-pr4 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr4.yml
    tags: salt

  - name: Deploy sa-pr5 minion
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/salt/sa-pr5.yml
    tags: salt

  - name: Deploy pupet-master
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /root/os/puppet/puppet-master.yml
    tags: puppet

  - name: Deploy pu-dv1 node
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/puppet/pu-dv1.yml
    tags: puppet

  - name: Deploy pu-dv2 node
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/puppet/pu-dv2.yml
    tags: puppet

  - name: Deploy pu-pr1 node
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/puppet/pu-pr1.yml
    tags: puppet

  - name: Deploy pu-pr2 node
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/puppet/pu-pr2.yml
    tags: puppet

  - name: Deploy pu-pr3 node
    k8s:
      kubeconfig: /home/masum/.kube/config
      namespace: default
      state: present
      src: /home/{{ user }}/files/puppet/pu-pr3.yml
    tags: puppet

        #  - name: Deploy jenkins
        #    k8s:
        #      kubeconfig: /home/masum/.kube/config
        #      namespace: default
        #      state: present
        #      src: /root/os/jenkins/jenkins.yml
