---
- import_playbook: common_pkg.yml
- import_playbook: controller.yml
- import_playbook: compute.yml
- import_playbook: compute_join_controller.yml
- import_playbook: image_build.yml
- import_playbook: docker_networks.yml
- import_playbook: build_containers.yml
