---
apiVersion: apps/v1
kind: Deployment
  #namespace: my-test
metadata:
  name: master-deploy
  labels:
     app: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: ubuntu-ssh:v1.0
