---
apiVersion: v1
kind: Pod
metadata:
  name: salt-master
  labels: 
    app: salt-master
spec:
  containers:
     - image: ubuntu-ssh:v1.0
       name: salt-master
       ports:
         - containerPort: 22
  restartPolicy: OnFailure
