---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels: 
    app: jenkins
spec:
  containers:
     - image: ubuntu-ssh:v1.0
       name: jenkins
       ports:
         - containerPort: 22
       volumeMounts:
         - name: root-disk-jenkins 
           mountPath: /mnt
  nodeSelector:
    kubernetes.io/hostname: "worker1"
  restartPolicy: Always
  volumes:
    - name: root-disk-jenkins 
      persistentVolumeClaim:
        claimName: pod-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: port-22-tcp
    protocol: TCP
    targetPort: 10022
    port: 22
