---
apiVersion: v1
kind: Pod
metadata:
  name: pu-dv1
  labels: 
    app: pu-dv1
spec:
  containers:
     - image: nginx:latest
       name: pu-dv1
       ports:
         - containerPort: 80
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pu-dv1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pu-dv1
  template:
    metadata:
      labels:
        app: pu-dv1
    spec:
      containers:
        - name: pu-dv1
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: pu-dv1
  namespace: default
  labels:
    app: pu-dv1
spec:
  type: ClusterIP
  selector:
    app: pu-dv1
  ports:
  - name: port-22-tcp
    protocol: TCP
    targetPort: 80 
    port: 9024
  externalIPs:
  - "192.168.20.168"
